function outPath = generate_clinical_report(reportData, fundusImg, gradcamMap, outHtmlPath)
%GENERATE_CLINICAL_REPORT  Generate one-page annotated report for <30s review.
%
%   outPath = GENERATE_CLINICAL_REPORT(reportData, fundusImg, gradcamMap, outHtmlPath)
%   creates a self-contained, publication-ready one-page clinical report
%   in HTML/PDF format and visual figure dashboard.
%
%   Inputs:
%     reportData  - Struct created by CLINICAL_REPORT_TEMPLATE
%     fundusImg   - (Optional) [H x W x 3] uint8 fundus image
%     gradcamMap  - (Optional) [H x W] double/single Grad-CAM heatmap [0, 1]
%     outHtmlPath - (Optional) Output filepath for HTML report
%
%   Design constraints:
%     - Information hierarchy optimized for rapid ophthalmologist triage:
%       a retina specialist can verify diagnosis and sign off in <30 seconds.
%     - Grounded explainability: AI attention is explicitly matched with
%       physical retinal lesion findings in a structured table.
%
%   See also CLINICAL_REPORT_TEMPLATE, RECAPTURE_MESSAGES.

    if nargin < 1 || isempty(reportData)
        reportData = clinical_report_template();
    end

    thisDir = fileparts(mfilename('fullpath'));
    projectRoot = fullfile(thisDir, '..', '..');

    if nargin < 4 || isempty(outHtmlPath)
        reportsDir = fullfile(projectRoot, 'reports');
        if ~isfolder(reportsDir)
            mkdir(reportsDir);
        end
        outHtmlPath = fullfile(reportsDir, sprintf('report_%s.html', reportData.patientId));
    end

    % Define urgency banner color styling
    switch reportData.predictedGrade
        case 0
            badgeBg = '#10b981'; % Green
            badgeText = 'NO DIABETIC RETINOPATHY (ICDR GRADE 0)';
            actionColor = '#065f46';
        case 1
            badgeBg = '#f59e0b'; % Amber
            badgeText = 'MILD NPDR (ICDR GRADE 1) - NON-REFERABLE';
            actionColor = '#92400e';
        case 2
            badgeBg = '#ea580c'; % Orange
            badgeText = 'MODERATE NPDR (ICDR GRADE 2) - REFERABLE DR';
            actionColor = '#9a3412';
        case 3
            badgeBg = '#dc2626'; % Red
            badgeText = 'SEVERE NPDR (ICDR GRADE 3) - URGENT REFERRAL';
            actionColor = '#991b1b';
        case 4
            badgeBg = '#991b1b'; % Deep Red
            badgeText = 'PROLIFERATIVE DR (ICDR GRADE 4) - EMERGENCY';
            actionColor = '#7f1d1d';
        otherwise
            badgeBg = '#6b7280';
            badgeText = 'UNGRADEABLE - RECAPTURE REQUIRED';
            actionColor = '#374151';
    end

    % Format probabilities
    probs = reportData.gradeProbabilities;
    if numel(probs) ~= 5 || any(~isfinite(probs))
        % No model distribution available. Drawing five bars anyway would show
        % the reader a confidence profile that was never computed.
        probBars = ['<div style="margin-top:6px; font-size:11px; color:#94a3b8;">' ...
                    'Per-grade distribution not available for this result.</div>'];
    else
    probBars = sprintf([ ...
        '<div style="display:flex; gap:4px; margin-top:6px; font-size:11px; text-align:center;">' ...
        '<div style="flex:1; background:#f3f4f6; padding:4px; border-radius:4px; border-top:3px solid #10b981;"><b>Grade 0</b><br>%.1f%%</div>' ...
        '<div style="flex:1; background:#f3f4f6; padding:4px; border-radius:4px; border-top:3px solid #f59e0b;"><b>Grade 1</b><br>%.1f%%</div>' ...
        '<div style="flex:1; background:#fef3c7; padding:4px; border-radius:4px; border-top:3px solid #ea580c;"><b>Grade 2</b><br><b>%.1f%%</b></div>' ...
        '<div style="flex:1; background:#f3f4f6; padding:4px; border-radius:4px; border-top:3px solid #dc2626;"><b>Grade 3</b><br>%.1f%%</div>' ...
        '<div style="flex:1; background:#f3f4f6; padding:4px; border-radius:4px; border-top:3px solid #991b1b;"><b>Grade 4</b><br>%.1f%%</div>' ...
        '</div>'], probs(1)*100, probs(2)*100, probs(3)*100, probs(4)*100, probs(5)*100);
    end

    % Build Evidence Table Rows
    evidenceHtml = '';
    for i = 1:size(reportData.evidenceTable, 1)
        row = reportData.evidenceTable(i, :);
        hotspot = row{1};
        finding = row{2};
        desc    = row{3};
        conf    = row{4};

        if strcmp(conf, 'HIGH')
            confTag = '<span style="background:#fee2e2; color:#991b1b; padding:2px 6px; border-radius:4px; font-size:10px; font-weight:bold;">HIGH</span>';
        elseif strcmp(conf, 'MODERATE')
            confTag = '<span style="background:#fef3c7; color:#92400e; padding:2px 6px; border-radius:4px; font-size:10px; font-weight:bold;">MOD</span>';
        else
            confTag = '<span style="background:#f3f4f6; color:#4b5563; padding:2px 6px; border-radius:4px; font-size:10px; font-weight:bold;">LOW</span>';
        end

        evidenceHtml = [evidenceHtml, sprintf([ ...
            '<tr style="border-bottom: 1px solid #e5e7eb; font-size: 11px;">' ...
            '<td style="padding:6px; font-weight:600; color:#1f2937;">%s</td>' ...
            '<td style="padding:6px; color:#2563eb; font-weight:600;">%s</td>' ...
            '<td style="padding:6px; color:#4b5563;">%s</td>' ...
            '<td style="padding:6px; text-align:center;">%s</td>' ...
            '</tr>'], hotspot, finding, desc, confTag)]; %#ok<AGROW>
    end

    % Embed the actual image. The box was a placeholder glyph, and a report
    % built for visual verification of Grad-CAM cannot be verified without it -
    % the reviewer would have to open the fundus image separately, which is the
    % whole cost the <30s target exists to remove.
    if nargin < 2, fundusImg = []; end
    if nargin < 3, gradcamMap = []; end
    imageBlock = embedOverlay(fundusImg, gradcamMap);

    % Build HTML Document
    html = sprintf([...
'<!DOCTYPE html>\n' ...
'<html lang="en">\n' ...
'<head>\n' ...
'<meta charset="UTF-8">\n' ...
'<title>DRishti-AI Screening Report — %s</title>\n' ...
'<style>\n' ...
'  @page { size: A4 portrait; margin: 10mm; }\n' ...
'  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #f9fafb; color: #111827; margin: 0; padding: 20px; font-size: 13px; line-height: 1.4; }\n' ...
'  .report-card { max-width: 900px; margin: 0 auto; background: #ffffff; border-radius: 8px; border: 1px solid #e5e7eb; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); overflow: hidden; }\n' ...
'  .header { background: #0f172a; color: #ffffff; padding: 14px 20px; display: flex; justify-content: space-between; align-items: center; }\n' ...
'  .header-title { font-size: 18px; font-weight: 700; letter-spacing: -0.5px; }\n' ...
'  .header-sub { font-size: 11px; color: #94a3b8; }\n' ...
'  .triage-banner { background: %s; color: white; padding: 10px 20px; font-weight: 700; font-size: 14px; text-align: center; letter-spacing: 0.5px; text-transform: uppercase; }\n' ...
'  .meta-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; padding: 12px 20px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; font-size: 11px; }\n' ...
'  .meta-item b { color: #64748b; font-size: 10px; text-transform: uppercase; display: block; margin-bottom: 2px; }\n' ...
'  .meta-note { padding: 8px 20px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; font-size: 10px; color: #64748b; line-height: 1.5; }\n' ...
'  .content-grid { display: grid; grid-template-columns: 1.1fr 1fr; gap: 16px; padding: 16px 20px; }\n' ...
'  .panel { border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; background: #ffffff; }\n' ...
'  .panel-title { font-size: 12px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 10px; display: flex; justify-content: space-between; }\n' ...
'  .image-box { background: #000000; border-radius: 6px; height: 260px; display: flex; align-items: center; justify-content: center; color: #94a3b8; font-size: 12px; position: relative; overflow: hidden; }\n' ...
'  .lesion-stat { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 12px; }\n' ...
'  .stat-card { background: #f8fafc; border: 1px solid #e2e8f0; padding: 8px; border-radius: 4px; text-align: center; }\n' ...
'  .stat-val { font-size: 16px; font-weight: 700; color: #0f172a; }\n' ...
'  .stat-lbl { font-size: 10px; color: #64748b; margin-top: 2px; }\n' ...
'  .evidence-table { width: 100%%; border-collapse: collapse; text-align: left; margin-top: 6px; }\n' ...
'  .evidence-table th { background: #f1f5f9; padding: 6px; font-size: 10px; color: #475569; text-transform: uppercase; }\n' ...
'  .rec-box { background: #eff6ff; border-left: 4px solid #3b82f6; padding: 12px 16px; margin-top: 10px; border-radius: 0 4px 4px 0; }\n' ...
'  .rec-title { font-size: 11px; font-weight: 700; color: #1d4ed8; text-transform: uppercase; margin-bottom: 4px; }\n' ...
'  .signoff-bar { background: #f8fafc; border-top: 1px solid #e2e8f0; padding: 12px 20px; display: flex; justify-content: space-between; align-items: center; }\n' ...
'  .btn-sign { background: #0f172a; color: white; border: none; padding: 8px 16px; border-radius: 4px; font-weight: 600; font-size: 12px; cursor: pointer; }\n' ...
'</style>\n' ...
'</head>\n' ...
'<body>\n' ...
'<div class="report-card">\n' ...
'  <div class="header">\n' ...
'    <div>\n' ...
'      <div class="header-title">DRishti-AI · Tele-Screening Report</div>\n' ...
'      <div class="header-sub">Rural Telemedicine Decision Support · MathWorks / SIH 2026</div>\n' ...
'    </div>\n' ...
'    <div style="text-align:right;">\n' ...
'      <span style="background:#1e293b; color:#38bdf8; padding:4px 8px; border-radius:4px; font-size:11px; font-weight:bold;">Review Target: &lt;30s</span>\n' ...
'    </div>\n' ...
'  </div>\n' ...
'  <div class="triage-banner">%s</div>\n' ...
'  <div class="meta-grid">\n' ...
'    <div class="meta-item"><b>Patient ID / Demographics</b>%s · %s / %s</div>\n' ...
'    <div class="meta-item"><b>Diabetes duration</b>%s</div>\n' ...
'    <div class="meta-item"><b>Examination</b>%s · %s</div>\n' ...
'    <div class="meta-item"><b>Primary Health Centre</b>%s</div>\n' ...
'    <div class="meta-item"><b>Camera</b>%s</div>\n' ...
'    <div class="meta-item"><b>Quality Gate (Mod 1)</b><span style="color:#059669; font-weight:bold;">%s %s</span></div>\n' ...
'  </div>\n' ...
'  <div class="meta-note"><b>Patient context is operator-entered, not measured.</b> The model reads the photograph and nothing else &mdash; age, sex, diabetes duration, centre and camera are recorded for the referral trail and are <b>not inputs to the grade</b>. Any field left blank at the point of care prints as &ldquo;not recorded&rdquo; rather than a plausible default.</div>\n' ...
'  <div class="content-grid">\n' ...
'    <div>\n' ...
'      <div class="panel">\n' ...
'        <div class="panel-title">Fundus Imaging & Grad-CAM Localization <span style="color:#64748b; font-size:10px;">%s</span></div>\n' ...
'        <div class="image-box">%s</div>\n' ...
'        <div style="font-size:11px; color:#64748b; margin-top:6px;">Disc: %s | Fovea: %s</div>\n' ...
'        <div style="margin-top:10px;">\n' ...
'          <div style="display:flex; justify-content:space-between; font-size:11px;">\n' ...
'            <b>Confidence:</b> <span style="font-weight:bold; color:#0f172a;">%s %s</span>\n' ...
'          </div>\n' ...
'          %s\n' ...
'        </div>\n' ...
'      </div>\n' ...
'    </div>\n' ...
'    <div>\n' ...
'      <div class="panel">\n' ...
'        <div class="panel-title">Quantified Retinal Biomarkers (Mod 2)</div>\n' ...
'        <div class="lesion-stat">\n' ...
'          <div class="stat-card"><div class="stat-val">%s</div><div class="stat-lbl">Microaneurysms</div></div>\n' ...
'          <div class="stat-card"><div class="stat-val">%s</div><div class="stat-lbl">Hemorrhages</div></div>\n' ...
'          <div class="stat-card"><div class="stat-val">%s</div><div class="stat-lbl">Hard Exudates</div></div>\n' ...
'        </div>\n' ...
'        <div class="panel-title" style="margin-top:12px;">Explainability Evidence Table (Mod 4)</div>\n' ...
'        <table class="evidence-table">\n' ...
'          <thead><tr><th>Hotspot</th><th>Biomarker</th><th>Clinical Observation</th><th>Confidence</th></tr></thead>\n' ...
'          <tbody>\n' ...
'            %s\n' ...
'          </tbody>\n' ...
'        </table>\n' ...
'      </div>\n' ...
'      <div class="rec-box">\n' ...
'        <div class="rec-title">Triage Action & Recommendation</div>\n' ...
'        <div style="font-size:12px; color:#1e3a8a; font-weight:500;">%s</div>\n' ...
'        <div style="font-size:11px; color:#3b82f6; margin-top:4px;"><b>Follow-up Window:</b> %s</div>\n' ...
'      </div>\n' ...
'    </div>\n' ...
'  </div>\n' ...
'  <div class="signoff-bar">\n' ...
'    <div style="font-size:11px; color:#64748b;">\n' ...
'      Status: <b style="color:#d97706;">%s</b> · Model: %s\n' ...
'    </div>\n' ...
'    <div style="display:flex; gap:8px;">\n' ...
'      <button class="btn-sign" style="background:#ffffff; color:#374151; border:1px solid #d1d5db;">Modify Grade</button>\n' ...
'      <button class="btn-sign" style="background:#059669;">Approve & Refer to DH (&lt;30s Sign-off)</button>\n' ...
'    </div>\n' ...
'  </div>\n' ...
'</div>\n' ...
'</body>\n' ...
'</html>\n'], ...
    reportData.patientId, badgeBg, badgeText, ...
    reportData.patientId, ageText(reportData.patientAge), reportData.patientGender, ...
    asText(reportData.diabetesDuration, '%s'), ...
    reportData.eyeExamined, reportData.screeningDate, ...
    reportData.screeningCenter, ...
    asText(reportData.cameraModel, '%s'), ...
    reportData.qualityStatus, qualityDetail(reportData), ...
    reportData.eyeExamined, imageBlock, ...
    pointText(reportData.lesions.opticDiscLocation), ...
    pointText(reportData.lesions.foveaLocation), ...
    asText(100 * reportData.calibratedConfidence, '%.1f%%'), confidenceQualifier(reportData), probBars, ...
    lesionCell(reportData.lesions.microaneurysmCount, '%d'), ...
    lesionCell(reportData.lesions.hemorrhageCount, '%d'), ...
    lesionCell(reportData.lesions.hardExudateAreaPct, '%.2f%%'), ...
    evidenceHtml, ...
    reportData.recommendedAction, reportData.followUpInterval, ...
    reportData.reviewStatus, modelLabel(reportData));

    % ---- Module 2 validation: what may be shown, and what may not ---------
    % Appended rather than threaded through the sprintf above: that format
    % string already carries ~20 positional arguments, and adding two more pairs
    % is a silent-misalignment bug waiting to happen.
    extra = [validationTableHtml(reportData) locationTableHtml(reportData)];
    if ~isempty(extra) && contains(html, '</body>')
        html = insertBefore(html, '</body>', extra);
    end

    % Write HTML file
    fid = fopen(outHtmlPath, 'w', 'native', 'UTF-8');
    if fid == -1
        error('Could not open file for writing: %s', outHtmlPath);
    end
    fprintf(fid, '%s', html);
    fclose(fid);

    fprintf('  Generated clinical report: %s\n', outHtmlPath);
    outPath = outHtmlPath;
end


function q = confidenceQualifier(reportData)
%CONFIDENCEQUALIFIER  Label the confidence honestly.
%
%   The report previously printed "(Platt Scaled)" unconditionally, while no
%   calibration existed anywhere in the codebase - a false label on a clinical
%   document. A calibrator now exists (models/calibrator.mat), but the report
%   must state which number it is actually showing.
%
%   It must also carry the domain caveat: the calibrator is fitted on APTOS,
%   and measured external validation shows the score distribution does not
%   transfer (sensitivity 90.3% internally, 31.2% on Messidor-2). A confidence
%   shown on an image from unseen equipment is not trustworthy.

    if ~isfield(reportData, 'predictedGrade') || ~isscalar(reportData.predictedGrade) || ...
            ~isfinite(reportData.predictedGrade)
        q = '(no grade produced - image rejected at the quality gate)';
    elseif isfield(reportData, 'calibrationApplied') && reportData.calibrationApplied
        q = '(Platt-calibrated on APTOS; not validated on other cameras)';
    else
        q = '(uncalibrated model output - not a probability)';
    end
end


function txt = lesionCell(value, fmt)
%LESIONCELL  Render a lesion statistic, or say why it is absent.
%
%   NaN means the detector behind this channel is not validated, so no number
%   is shown. Printing 0 there would be a clinical assertion - "we looked and
%   found none" - which is exactly what an unvalidated detector cannot support.
%
%   Measured per-lesion precision against IDRiD ground truth:
%       hard exudates 0.549 (reported; was 0.595, corrected - see
%       segmentExudates.m) | haemorrhages 0.034 | microaneurysms 0.021 |
%       soft exudates never measured.
%
%   A count at 2-3% precision on a clinical document is a fabricated finding
%   wearing an authoritative format.

    if isnan(value)
        txt = '<span style="font-size:13px; color:#94a3b8;">not validated</span>';
    else
        txt = sprintf(fmt, value);
    end
end


function t = asText(value, fmt)
%ASTEXT  Format a number for the report, or say it is absent.
%
%   Every value reaching the big SPRINTF must already be text. MATLAB's sprintf
%   flattens its arguments into one vector and recycles the format, so a char
%   array handed to a numeric specifier is expanded to ONE NUMBER PER CHARACTER
%   and silently consumes that many specifiers. When patientAge became the
%   string 'not recorded' against a %d, it ate twelve specifiers and every field
%   after it shifted - the disc coordinate ended up rendered as a lesion count.
%   Formatting here, and using %s throughout, makes that failure impossible.

    if isempty(value) || (isnumeric(value) && ~isfinite(value))
        t = 'not recorded';
    elseif ischar(value) || isstring(value)
        t = char(value);
    else
        t = sprintf(fmt, value);
    end
end


function t = ageText(value)
    if isnumeric(value) && isscalar(value) && isfinite(value)
        t = sprintf('%dY', round(value));
        return
    end

    t = asText(value, '%s');

    % An age typed into the web form arrives as TEXT, so "52" would print bare
    % while a numeric 52 prints "52Y" - the same field rendering two ways
    % depending on which caller filled it. Normalise only a plain integer:
    % "not recorded", "unknown" and anything else must pass through untouched
    % rather than acquire a spurious unit.
    if ~isempty(regexp(t, '^\s*\d{1,3}\s*$', 'once'))
        t = [strtrim(t) 'Y'];
    end
end


function t = pointText(pt)
%POINTTEXT  Pixel coordinates, or a statement that they were not found.
    if numel(pt) ~= 2 || any(~isfinite(pt))
        t = 'not located';
    else
        t = sprintf('[%d, %d]', round(pt(1)), round(pt(2)));
    end
end


function t = qualityDetail(reportData)
%QUALITYDETAIL  The quality number, named for what it actually is.
%
%   The template printed '(Score: 0.88)', implying a normalised [0,1] focus
%   score. The pipeline has no such score: it measures Laplacian variance on a
%   resolution-normalised image, which is unbounded and not a probability.
%   Printing it under a 0-1 label would misrepresent the metric, so it is
%   labelled as sharpness and omitted entirely when unavailable.

    if ~isfield(reportData, 'sharpness') || isempty(reportData.sharpness) || ...
            ~isfinite(reportData.sharpness)
        t = '';
        return
    end
    t = sprintf(' (sharpness %.0f', reportData.sharpness);
    if isfield(reportData, 'sharpnessBand') && ~isempty(reportData.sharpnessBand)
        t = [t ', ' char(reportData.sharpnessBand) ' band'];
    end
    t = [t ')'];
end

function h = embedOverlay(fundusImg, gradcamMap)
%EMBEDOVERLAY  Inline the fundus/Grad-CAM composite as a base64 data URI.
%
%   The report has to be one self-contained file. A screening report that
%   references an image on the local disk arrives at the district hospital as a
%   broken image icon, so the pixels travel inside the HTML.
%
%   Downscaled to 520px on the long side: the reviewer is confirming WHERE the
%   model looked, not counting microaneurysms, and a 4288px IDRiD frame would
%   add ~4 MB of base64 to a document that must open quickly over a rural link.

    if isempty(fundusImg)
        h = ['<div style="text-align:center; padding:20px; color:#94a3b8;">' ...
             '<b>No image supplied</b><br><span style="font-size:11px;">' ...
             'Grad-CAM localisation cannot be verified from this report.</span></div>'];
        return
    end

    img = fundusImg;
    if ~isempty(gradcamMap) && isequal(size(gradcamMap,1:2), size(img,1:2))
        img = compositeOverlay(img, gradcamMap);
    end

    scale = 520 / max(size(img,1), size(img,2));
    if scale < 1, img = imresize(img, scale); end
    if ~isa(img, 'uint8'), img = im2uint8(img); end

    tmp = [tempname '.png'];
    imwrite(img, tmp);
    fid = fopen(tmp, 'r');
    bytes = fread(fid, Inf, '*uint8');
    fclose(fid);
    delete(tmp);

    h = sprintf(['<img src="data:image/png;base64,%s" ' ...
                 'style="max-width:100%%; max-height:100%%; object-fit:contain;" ' ...
                 'alt="Fundus image with Grad-CAM overlay">'], ...
                matlab.net.base64encode(bytes));
end


function t = modelLabel(reportData)
    if isfield(reportData,'modelDescription') && ~isempty(reportData.modelDescription)
        t = char(reportData.modelDescription);
    else
        t = 'model not identified';
    end
end


function h = validationTableHtml(rd)
%VALIDATIONTABLEHTML  Every lesion channel, passed or failed, with its numbers.
%
%   Failures are shown, not omitted. A report listing only the channel that
%   worked implies the others were never tried, which overstates the system by
%   omission - and the fact that three of four detectors are unfit to display is
%   one of the more important things this document can tell a reviewer.

    h = '';
    if ~isfield(rd, 'detectorValidation') || isempty(rd.detectorValidation)
        return
    end
    rows = rd.detectorValidation;

    body = '';
    for i = 1:size(rows, 1)
        name = rows{i,1}; p = rows{i,2}; r = rows{i,3}; f1 = rows{i,4};
        verdict = rows{i,5};
        passed = startsWith(verdict, 'VALIDATED');
        if passed
            tag = ['<span style="background:#dcfce7;color:#14532d;padding:2px 6px;' ...
                   'border-radius:4px;font-size:10px;font-weight:bold;">DISPLAYED</span>'];
            rowStyle = 'color:#1f2937;';
        else
            tag = ['<span style="background:#f3f4f6;color:#6b7280;padding:2px 6px;' ...
                   'border-radius:4px;font-size:10px;font-weight:bold;">NOT VALIDATED</span>'];
            rowStyle = 'color:#9ca3af;';
        end
        body = [body sprintf([ ...
            '<tr style="border-bottom:1px solid #e5e7eb;font-size:11px;%s">' ...
            '<td style="padding:6px;font-weight:600;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td></tr>'], ...
            rowStyle, name, num3(p), num3(r), num3(f1), tag)]; %#ok<AGROW>
    end

    h = ['<div style="margin:14px 18px;padding:12px 14px;background:#f8fafc;' ...
         'border:1px solid #e5e7eb;border-radius:6px;">' ...
         '<div style="font-size:12px;font-weight:700;color:#1f2937;margin-bottom:2px;">' ...
         'Module 2 detector validation</div>' ...
         '<div style="font-size:10.5px;color:#6b7280;margin-bottom:8px;">' ...
         'Per-lesion precision / recall / F1 on the held-out IDRiD test split, ' ...
         'FOV-masked, 8-connected component matching, micro-averaged. A channel is ' ...
         'displayed only if it cleared a bar frozen before the test was run ' ...
         '(config/lesion_validation_thresholds.json).</div>' ...
         '<table style="width:100%;border-collapse:collapse;">' ...
         '<tr style="background:#f1f5f9;font-size:10px;color:#475569;text-align:left;">' ...
         '<th style="padding:5px;">Channel</th>' ...
         '<th style="padding:5px;text-align:center;">Precision</th>' ...
         '<th style="padding:5px;text-align:center;">Recall</th>' ...
         '<th style="padding:5px;text-align:center;">F1</th>' ...
         '<th style="padding:5px;text-align:center;">Status</th></tr>' ...
         body '</table></div>'];
end


function h = locationTableHtml(rd)
%LOCATIONTABLEHTML  Where the validated lesions are, in disc diameters.

    h = '';
    if ~isfield(rd, 'lesionLocations'), return; end
    locs = rd.lesionLocations;

    if isempty(locs)
        h = ['<div style="margin:14px 18px;padding:10px 14px;background:#f8fafc;' ...
             'border:1px solid #e5e7eb;border-radius:6px;font-size:11px;color:#6b7280;">' ...
             '<b style="color:#1f2937;">Validated lesion locations</b><br>' ...
             'No validated lesions were located in this image. This is not a statement ' ...
             'that the retina is clear - only the validated channel is capable of ' ...
             'placing a finding, and it finds about one lesion in seven.</div>'];
        return
    end

    body = '';
    for i = 1:size(locs, 1)
        c = locs{i,5};
        body = [body sprintf([ ...
            '<tr style="border-bottom:1px solid #e5e7eb;font-size:11px;">' ...
            '<td style="padding:6px;color:#2563eb;font-weight:600;">%s</td>' ...
            '<td style="padding:6px;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td>' ...
            '<td style="padding:6px;text-align:center;">%s</td>' ...
            '<td style="padding:6px;text-align:center;color:#9ca3af;">%d, %d</td></tr>'], ...
            locs{i,1}, locs{i,2}, num2(locs{i,3}), num4(locs{i,4}), ...
            c(1), c(2))]; %#ok<AGROW>
    end

    h = ['<div style="margin:14px 18px;padding:12px 14px;background:#ffffff;' ...
         'border:1px solid #e5e7eb;border-radius:6px;">' ...
         '<div style="font-size:12px;font-weight:700;color:#1f2937;margin-bottom:2px;">' ...
         'Validated lesion locations</div>' ...
         '<div style="font-size:10.5px;color:#6b7280;margin-bottom:8px;">' ...
         'Largest lesions from validated channels only. Distances are in DISC ' ...
         'DIAMETERS, not pixels, so they mean the same thing on every camera.</div>' ...
         '<table style="width:100%;border-collapse:collapse;">' ...
         '<tr style="background:#f1f5f9;font-size:10px;color:#475569;text-align:left;">' ...
         '<th style="padding:5px;">Lesion</th><th style="padding:5px;">Quadrant</th>' ...
         '<th style="padding:5px;text-align:center;">Dist. to fovea (DD)</th>' ...
         '<th style="padding:5px;text-align:center;">Area (DD&sup2;)</th>' ...
         '<th style="padding:5px;text-align:center;">Centroid px</th></tr>' ...
         body '</table></div>'];
end


function t = num3(v)
    if isnumeric(v) && isscalar(v) && isfinite(v), t = sprintf('%.3f', v); else, t = 'n/a'; end
end

function t = num2(v)
    if isnumeric(v) && isscalar(v) && isfinite(v), t = sprintf('%.1f', v); else, t = 'n/a'; end
end

function t = num4(v)
    if isnumeric(v) && isscalar(v) && isfinite(v), t = sprintf('%.4f', v); else, t = 'n/a'; end
end
