function th = loadQualityThresholds(forceReload)
%LOADQUALITYTHRESHOLDS  Module 1 gate thresholds, cached after first read.
%
%   th = LOADQUALITYTHRESHOLDS() reads config/quality_thresholds.json.
%   th = LOADQUALITYTHRESHOLDS(true) bypasses the cache after recalibrating.
%
%   The file is generated by CALIBRATEQUALITYTHRESHOLDS from measured
%   distributions across all four corpora - by the same MATLAB code that
%   enforces the thresholds, so there is no cross-language transfer to get
%   wrong. Regenerate with:
%
%       calibrateQualityThresholds('nPerCorpus', 120)
%
%   Returns
%     th.canonicalFovPx     reference FOV diameter for sharpness normalisation
%     th.sharpness.byBand   per-band .reject / .borderline (small|mid|large)
%     th.sharpness.reject   pooled fallback
%     th.illumination, th.glare, th.contrast, th.exposure
%
%   fov_coverage is deliberately absent: it is a camera fingerprint, not a
%   quality signal, so it is never gated. See CALIBRATEQUALITYTHRESHOLDS.
%
%   See also ASSESSQUALITY, GATEIMAGE, CALIBRATEQUALITYTHRESHOLDS.

    arguments
        forceReload (1,1) logical = false
    end

    persistent cached
    if ~isempty(cached) && ~forceReload
        th = cached;
        return
    end

    cfg = drishti_paths();
    f = fullfile(cfg.projectRoot, 'config', 'quality_thresholds.json');
    if ~isfile(f)
        error('drishti:missingThresholds', ...
            ['%s not found. Generate it with:\n' ...
             '    calibrateQualityThresholds()'], f);
    end

    raw = jsondecode(fileread(f));

    th.canonicalFovPx = raw.canonical_fov_px;

    th.sharpness.reject     = raw.sharpness.reject_below;
    th.sharpness.borderline = raw.sharpness.borderline_below;

    % Per-band absolute thresholds, measured rather than assumed. A single
    % cut-off does not survive a 6.7x resolution range even after FOV
    % normalisation - the residual correlation is about -0.43.
    bands = {'small', 'mid', 'large'};
    for k = 1:numel(bands)
        b = bands{k};
        if isfield(raw.sharpness, 'by_band') && isfield(raw.sharpness.by_band, b)
            th.sharpness.byBand.(b).reject     = raw.sharpness.by_band.(b).reject;
            th.sharpness.byBand.(b).borderline = raw.sharpness.by_band.(b).borderline;
        else
            th.sharpness.byBand.(b).reject     = th.sharpness.reject;
            th.sharpness.byBand.(b).borderline = th.sharpness.borderline;
        end
    end

    th.illumination.reject     = raw.illumination_uniformity.reject_above;
    th.illumination.borderline = raw.illumination_uniformity.borderline_above;

    th.glare.reject     = raw.glare.reject_above;
    th.glare.borderline = raw.glare.borderline_above;

    th.contrast.reject = raw.contrast.reject_below;

    th.exposure.darkReject         = raw.exposure.dark_reject;
    th.exposure.brightReject       = raw.exposure.bright_reject;
    th.exposure.darkFractionReject = raw.exposure.dark_fraction_reject;

    cached = th;
end
